Repository OpenCHAMI/ochami, pull requests merged in 2025-04, with the labels that each got.

#20 fix(client): use format.UnmarshalData to unmarshal file bytes
  pkg/client/client.go
Labels: bug

#19 feat!: update cloud-init commands to match v1 API
  cmd/cloud_init-config-add.go
  cmd/cloud_init-config-delete.go
  cmd/cloud_init-config-get.go
  cmd/cloud_init-config-update.go
  cmd/cloud_init-config.go
  cmd/cloud_init-data-get.go
  cmd/cloud_init-defaults-get.go
  cmd/cloud_init-defaults-set.go
  cmd/cloud_init-defaults.go
  cmd/cloud_init-group-add.go
  cmd/cloud_init-group-delete.go
  cmd/cloud_init-group-get.go
  cmd/cloud_init-group-render.go
  cmd/cloud_init-group-set.go
  cmd/cloud_init-group.go
  cmd/cloud_init-node-get.go
  cmd/cloud_init-node-set.go
  cmd/cloud_init-node.go
  cmd/cloud_init.go
  cmd/lib.go
  go.mod
  go.sum
  man/ochami-cloud-init.1.sc
  pkg/client/ci/ci.go
  pkg/client/client.go
Labels: enhancement

#25 feat!: move discover cmd to discover-static command
  cmd/discover-static.go
  cmd/discover.go
  man/ochami-discover.1.sc
Labels: enhancement

#29 Update smd rfe help output and man page entry
  cmd/smd-rfe-add.go
  man/ochami-smd.1.sc
Labels: good first issue
